version: "3"
services:
  prod-db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file:
      - docker/env/db.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - prod-percona-data:/var/lib/mysql

  blog-migrate:
    image: dacheson/sample-blog-migrate:latest
    env-file:
      - docker/env/sample-blog-prod.env

  blog:
    image: dacheson/sample-blog:latest
    env_file:
      - docker/env/sample-blog-prod.env
    ports:
      - "80:8000"
    restart: always

volumes:
  prod-percona-data:
