version: "3"
services:
  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file:
      - docker/env/db.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - percona-data:/var/lib/mysql

  dev:
    image: dacheson/sample-blog-dev:1.0.1
    env_file:
      - docker/env/sample-blog-dev.env
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/home/node/dev
    stdin_open: true
    tty: true

volumes:
  percona-data:
